api:
  spotify:
    client:
      id: 21a967fe3c2d43b39c3b7a4fd8c87752
      secret: 23cc910c0039432b89f8fda30a4a0592
server:
  port: 8081
spring:
  cache:
    type: redis
    redis:
      key-prefix: false
      time-to-live: 100000
  redis:
    host: localhost
    port=6379: